import type { Metadata } from "next";
import "./globals.css";
import { GeistSans } from "geist/font/sans";
import clsx from "clsx";
import '@mantine/dropzone/styles.css';
import { Inter } from "next/font/google";
import { MantineProvider, ColorSchemeScript } from '@mantine/core';

import { Providers as NextUIProvider } from "@/app/providers";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={clsx(GeistSans.variable, inter.className, "antialiased")}
      >
        <MantineProvider>{children}</MantineProvider>
      </body>
    </html>
  );
}
